- hosts: "{{ HOSTS }}"
  become: yes
  gather_facts: "{{ GATHER_FACTS | default('yes')  }}"

  roles:
  - role: pmm-agent
    tags:
    - pmm-agent
  - role: zfs-exporter
    tags:
    - zfs-exporter
